site_name: wikbase extracted sparql examples
nav:
  - Home: ./index.md
  - WikiData: ./examples/wikidata/index.md
  - License: ./LICENSE.md
  - Readme: ./Code_Instructions.md
site_dir: _site
plugins:
  - mermaid2

